apiVersion: v1
kind: Namespace
metadata:
  name: development
  labels:
    name: development
---
apiVersion: v1
kind: Namespace
metadata:
  name: production
  labels:
    name: production
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm
  namespace: development
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: llm
  namespace: production
