apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.4.0-alpine3.20
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "2Gi"  # Maximum memory allowed
            cpu: "0.5"
          requests:
            memory: "2Gi"  # Initial memory request
            cpu: "0.5"       # Initial CPU request
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: platform
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379




