apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: platform
type: Opaque
data:
  postgres-user: ZGF0YQ==
  postgres-password: aGVzbG8=
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard-rwo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
      - name: postgres
        image: postgres:16.0
        imagePullPolicy: IfNotPresent
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              key: postgres-user
              name: postgres-secret
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              key: postgres-password
              name: postgres-secret
        - name: POSTGRES_DB
          value: postgresdb
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
          subPath: postgres   
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      resources:
        limits:
          memory: "2Gi"  # Maximum memory allowed
          cpu: "0.5"
        requests:
          memory: "2Gi"  # Initial memory request
          cpu: "0.5"       # Initial CPU request
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgresql
spec:
  selector:
    app: postgres
  ports:
  - name: tcp-port
    protocol: TCP
    port: 5432
    targetPort: 5432
