apiVersion: apps/v1
kind: Deployment
metadata:
  name: litellm
  namespace: platform
  labels:
    app: litellm
spec:
  selector:
    matchLabels:
      app: litellm
  template:
    metadata:
      labels:
        app: litellm
    spec:
      serviceAccountName: llm
      containers:
      - name: litellm
        image: us-central1-docker.pkg.dev/DUMMY_PROJECT/containers/proxy:2024-09-25
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health/liveliness
            port: 4000
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        readinessProbe:
          httpGet:
            path: /health/readiness
            port: 4000
          initialDelaySeconds: 120
          periodSeconds: 15
          successThreshold: 1
          failureThreshold: 3
          timeoutSeconds: 10
        ports:
        - containerPort: 4000
        env:
        - name: LITELLM_MASTER_KEY
          value: "sk-1234"
        - name: DATABASE_URL
          value: "postgresql://data:heslo@postgres.platform.svc.cluster.local:5432/postgres"
        resources:
          limits:
            memory: "2Gi"  # Maximum memory allowed
            cpu: "0.5"
          requests:
            memory: "2Gi"  # Initial memory request
            cpu: "0.5"       # Initial CPU request
---
apiVersion: v1
kind: Service
metadata:
  name: llm
  namespace: platform
  annotations:
    networking.gke.io/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: litellm
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 4000
